name: Build PacMan IPA for TrollStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install xcodegen

    - name: Generate Xcode project
      run: |
        echo "name: PacMan
        targets:
          PacMan:
            type: application
            platform: iOS
            deploymentTarget: 15.0
            sources:
              - path: Sources
            settings:
              base:
                PRODUCT_BUNDLE_IDENTIFIER: com.ditnavn.pacman
                CODE_SIGNING_ALLOWED: NO
                CODE_SIGNING_REQUIRED: NO
        " > project.yml
        xcodegen generate

    - name: Build unsigned IPA
      run: |
        xcodebuild -project PacMan.xcodeproj -scheme PacMan -configuration Release -archivePath build/PacMan.xcarchive archive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
        xcodebuild -exportArchive -archivePath build/PacMan.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
      env:
        EXPORT_OPTIONS_PLIST: |
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>teamID</key>
            <string></string>
            <key>generateAppStoreInformation</key>
            <false/>
            <key>destination</key>
            <string>export</string>
          </dict>
          </plist>

    - name: Move IPA to output
      run: |
        mv build/PacMan.ipa build/PacMan_unsigned.ipa

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: PacMan-IPA
        path: build/PacMan_unsigned.ipa